### ISSUE TITLE
material design icons are not displayed in dropdown

### ISSUE THREAD

**Issue by fabienmoyon** [linagora/esn-frontend-common-libs#109]
### CURRENT

1. In the sidebar, dropdown `settings-overlay` component don't display material design icons

![Capture d’écran de 2020-08-25 15-25-51](https://user-images.githubusercontent.com/11298249/91424474-1c6fa180-e85a-11ea-98d6-3afd5ac020a9.png)

1. In the header, dropdown `profile-menu` component don't display material design icons

![Capture d’écran de 2020-08-27 11-40-57](https://user-images.githubusercontent.com/11298249/91424544-390bd980-e85a-11ea-8607-8c4bf9e1c99f.png)

### EXPECTED

![Capture d’écran de 2020-08-26 15-56-53](https://user-images.githubusercontent.com/11298249/91424471-1bd70b00-e85a-11ea-899d-aee1187cca21.png)

![Capture d’écran de 2020-08-25 15-28-02](https://user-images.githubusercontent.com/11298249/91424473-1c6fa180-e85a-11ea-8607-40108a02cd31.png)

### TO DO

- [ ] display material design icons

**Comment by tuanlc** [comment]
Information: This error appears only on dev platform with production deployment

**Comment by tuanlc** [comment]
The reason, in the frontend, we setup default icon for angular material:
```javascript
$mdIconProvider.defaultIconSet('images/mdi/mdi.svg', 24);
```

And this performs a request to ESN backend to get the `mdi.svg` resource.

### Why does it work on devServer? 

Because with Webpack devServer proxy, we forward the request from `localhost:9900` to server base URL, then the request is:
```
https://dev.open-paas.org/images/mdi/mdi.svg
```
And it works like before in the old code base

### Why production deployment on DEV server doesn't work?
Because the base URL of SPA has additional route: https://dev.open-paas.org/contacts/ Then the mdi request becomes:
```
https://dev.open-paas.org/contacts/images/mdi/mdi.svg
```
And the request is 404

**Comment by tuanlc** [comment]
### Solution:
We need to make mdi.svg available on any mode of deployment. And we should not send the request to server to get this kind of resource like we did for templates.

And because we have 2 places to set default icon for material at [core](https://github.com/OpenPaaS-Suite/esn-frontend-common-libs/blob/main/src/frontend/js/modules/header/profile-menu/profile-menu.config.js) and [inbox](https://github.com/OpenPaaS-Suite/esn-frontend-inbox/blob/main/src/linagora.esn.unifiedinbox/app/config.js#L8)

So solution is serving the mdi.svg in frontend and having 1 global config block to set default icon

Steps:

- [x]  Serve `mdi.svg` in `esn-frontend-common-libs`
- [x]   Have 1 config block to set default icon in esn.material module
- [x]   Require esn.material module in SPAs
- [x]  Remove the config in inbox & esn.user-profile modules
