### ISSUE TITLE
Remove search provider dropdown 

### ISSUE THREAD

**Issue by fabienmoyon** [linagora/esn-frontend-common-libs#110]
### CURRENT 

Before the split, the global search was able to provide a search provider per module on the platform. 

![Capture d’écran de 2020-08-27 14-38-33](https://user-images.githubusercontent.com/11298249/91447665-3a003380-e879-11ea-8920-cfcdf71c2cf5.png)

### EXPECTED

Now each module is displayed on this own tab so we don't need anymore to be able to chosse the search provider. We can only search in to the module displayed.

![Capture d’écran de 2020-08-27 14-38-52](https://user-images.githubusercontent.com/11298249/91447676-3d93ba80-e879-11ea-861b-69fccf2ed894.png)

### TO DO 

- [ ] Remove `All` search provider

- [ ] Remove on each module the dropdown provider

**Comment by tuanlc** [comment]
I don't think we should remove them. `Search all` is a nice feature. 

@fabienmoyon can you explain why?

**Comment by rezk2ll** [comment]
> I don't think we should remove them. `Search all` is a nice feature.
> 
> @fabienmoyon can you explain why?

I think it doesn't make any sense anymore, since the dropdown list only has 2 options `All` and the current SPA ( ie contact ).
I think selecting all is the same as selecting the current SPA, so it kinda feels meaningless since you can't search in other SPAs/services.
![image](https://user-images.githubusercontent.com/6764881/91544205-4fc43600-e917-11ea-9d49-a8e1d2d786ba.png)


if we decide to keep it we need to provide each SPA with the list of providers that can be searched and a way to communicate with each other.
